apiVersion: v1
kind: Service
metadata:
  name: universal-messaging
  namespace: insurance
  labels:
    app: messaging
    version: "10.15"
  annotations:
      prometheus.io/scrape: 'true'  
      prometheus.io/port: '9200'     
spec:
  selector:
    app: messaging
    version: "10.15"
  ports:
    - name: tcp-nsp
      port: 9000
      targetPort: 9000
      nodePort: 30990
    - name: http-metrics
      port: 9200
      targetPort: 9200
      nodePort: 30991      
  type: NodePort