apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apigw-storage
  labels:
    app: api-gateway
  namespace: insurance
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi