apiVersion: batch/v1
kind: Job
metadata:
  name: job-asset-import-gateway 
  namespace: insurance
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false" 
    spec:
      restartPolicy: Never
      containers:
      - name: asset-import-gateway
        image: redhat/ubi8-minimal
        command: 
        - "sh"
        - "-c"
        - |
          cd /tmp
          cp /tmp/* /scripts/
          cd /scripts
          chmod 755 import.sh
          ./import.sh
        volumeMounts:
          - mountPath: /scripts
            name: create-dir
          - mountPath: /tmp
            name: import-script                    
      volumes:
        - name: import-script
          configMap:
              name: apigw-script-configmap   
        - name: create-dir
          emptyDir: {}