FROM sagcr.azurecr.io/webmethods-microservicesruntime:10.15.0.0-ubi
USER sagadmin
ADD --chown=sagadmin assets/insurance/insurance-usecase-type-apigw/applications/assessments/assessments/sourcecode/msr-packages/ /opt/softwareag/IntegrationServer/packages/