{
 "title": "METRICS - SAG PRODUCT RUNTIME OVERVIEW",
 "tags": [
  "msr",
  "um",
  "tsa",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\",namespace=~\"$namespace\"},pod)"
    }
   },
   { "name": "datasource", "query": "${VAR_DATASOURCE}" },
   {
    "name": "tsa_cluster",
    "query": {
     "query": "label_values(sag_bm_server_live_object_count,cluster_name)"
    }
   },
   {
    "name": "tsa_server",
    "query": {
     "query": "label_values(sag_bm_server_live_object_count{cluster_name=~\"$tsa_cluster\"},server_name)"
    }
   },
   {
    "name": "cache_mgr_name",
    "query": {
     "query": "label_values(sag_bm_cache_search_rate{cluster_name=~\"$tsa_cluster\"},cache_manager_name)"
    }
   },
   {
    "name": "cache_name",
    "query": {
     "query": "label_values(sag_bm_cache_search_rate{cluster_name=~\"$tsa_cluster\"},cache_name)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=~\"$cluster\",namespace=~\"$namespace\"},label_app)"
    }
   },
   {
    "name": "http_status_codes",
    "query": {
     "query": "label_values({__name__=~\"sag_apigw_api_tx_error_count|sag_is_service_requests_total\"},code)"
    }
   },
   {
    "name": "api_name",
    "query": {
     "query": "label_values(sag_apigw_api_tx_count,api_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API GATEWAY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ACTIVE APIs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sag_apigw_api_tx_count{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API - TOTAL TRANSACTIONS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(sag_apigw_tx_count{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API - TOTAL ERRORS [ 4xx | 5xx ]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(sag_apigw_tx_error_count{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\",code=~\"$http_status_codes\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API WITH AVG RESPONSE TIME [>60s]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sag_apigw_api_avg_response_time{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\"} > 60000) by(api_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNEXPECTED ERRORS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(sag_apigw_exec_error_count{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API  TRANSACTIONS [ ALL ]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(sag_apigw_api_tx_count{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\",api_name=~\"$api_name\"}[$__range])) by(api_name) > 0)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "API  ERROR TXANSACTIONS [ 4.X | 5.X ]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(sag_apigw_api_tx_error_count{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\",code=~\"4.*|5.*\",api_name=~\"$api_name\"}[$__range])) by(api_name)) > 0",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "API AVERAGE RESPONSE TIME",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sag_apigw_api_avg_response_time{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\",api_name=~\"$api_name\"}",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "API AVERAGE BACKEND RESPONSE TIME",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sag_apigw_api_avg_backend_response_time{node=~\"$node\",cluster=~\"$cluster\",namespace=~\"$namespace\",api_name=~\"$api_name\"}",
     "legendFormat": "{{api_name}} - {{code}}"
    }
   ]
  },
  { "title": "MSR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "RUNNING APPLICATIONS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{namespace=~\"$namespace\"}==1) by(app))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNAVAILABLE APPLICATIONS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=~\"$namespace\"}==0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APPS (MEMORY > 70%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((((sag_is_used_memory_bytes{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}/1024/1024) / (sag_is_max_memory_bytes{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}/1024/1024) ) * 100) > 70)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APPS (CPU > 70%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sag_is_server_proc_sys_percent{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"} >= 70)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APPS (SERVER THREADS > 70%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(((sag_is_server_threads{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"} / sag_is_server_maxthreads{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) * 100 > 70 ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APPS (SERVICE ERRORS > 50)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(increase(sag_is_number_service_errors{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}[$__range])) by(app,pod) > 50)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "RUNNING PODS - DETAILS",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\",app=~\"$app\",node=~\"$node\",cluster=~\"$cluster\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNAVAILABLE APPS - DETAILS",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 35 },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\",app=~\"$app\",node=~\"$node\",cluster=~\"$cluster\"}==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APPS - MEMORY > 50% - DETAILS",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "(((sag_is_used_memory_bytes{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}/(1024 * 1024)) / (sag_is_max_memory_bytes{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}/(1024 * 1024)) ) * 100 ) > 50",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APPS (CPU > 50%) - DETAILS",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sag_is_server_proc_sys_percent{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"} >= 50",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APPS (THREADS > 70%) - DETAILS",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "((sag_is_server_threads{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"} / sag_is_server_maxthreads{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) * 100 > 70 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APPS (SERVICE ERRORS > 50) - DETAILS",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 35 },
   "targets": [
    {
     "expr": "floor(sum(increase(sag_is_number_service_errors{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}[$__range])) by(app,pod) > 50 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONSOLIDATED DATA (MSR)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "(((sag_is_used_memory_bytes{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}/(1024 * 1024)) / (sag_is_max_memory_bytes{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}/(1024 * 1024)) ) * 100 ) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sag_is_server_proc_sys_percent{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sag_is_server_threads{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sag_is_server_maxthreads{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sag_is_number_service_errors{app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\"}",
     "legendFormat": "test"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 } },
  { "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 } },
  {
   "title": "TRANSACTIONS  BY APP 5.X",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sag_is_service_requests_total{apiCat=~\"API_REST\",code=~\"5.*\",node=~\"$node\",namespace=~\"$namespace\",app=~\"$app\",pod=~\"$pod\",cluster=~\"$cluster\"}) by(app,code,version)",
     "legendFormat": "{{app}} - {{version}}"
    }
   ]
  },
  {
   "title": "SERVICE ERRORS  BY APP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(delta(sag_is_service_number_errors[$__range])) > 0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 } },
  { "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 } },
  {
   "title": "SERVICES BY STATUS CODE ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sag_is_service_requests_total{apiCat=~\"API_REST\",node=~\"$node\",app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\",code=~\"$http_status_codes\"}) by(app,code,version,service) > 0",
     "legendFormat": "{{app}} - {{version}} - {{service}} | {{code}}"
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 } },
  { "gridPos": { "h": 11, "w": 13, "x": 0, "y": 76 } },
  { "gridPos": { "h": 11, "w": 6, "x": 13, "y": 76 } },
  { "gridPos": { "h": 11, "w": 5, "x": 19, "y": 76 } },
  { "gridPos": { "h": 10, "w": 6, "x": 0, "y": 87 } },
  { "gridPos": { "h": 10, "w": 6, "x": 6, "y": 87 } },
  { "gridPos": { "h": 10, "w": 6, "x": 12, "y": 87 } },
  { "gridPos": { "h": 10, "w": 6, "x": 18, "y": 87 } },
  { "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 } },
  { "gridPos": { "h": 9, "w": 6, "x": 12, "y": 97 } },
  { "gridPos": { "h": 9, "w": 6, "x": 18, "y": 97 } },
  { "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 } },
  { "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 } },
  { "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 } },
  { "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 } },
  {
   "title": "Universal Messaging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "collapsed": true,
   "panels": [
    { "title": "UM SERVER MEMORY [USED/TOTAL]", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 } },
    { "title": "BYTES (IN/OUT)", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 } },
    { "title": "CPU USAGE", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 } },
    { "title": "ALLOCATED THREADS", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 } },
    { "title": "STALLED THREADS", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 } },
    { "title": "TOTAL THREADS", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 } },
    { "title": "PUBLISHED EVENTS", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 36 } },
    { "title": "CONSUMED EVENTS", "gridPos": { "h": 7, "w": 5, "x": 5, "y": 36 } },
    { "title": "EVENTS (IN TOPICS)", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 36 } },
    { "title": "DURABLE - OUTSTANDING EVENTS", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 36 } },
    { "title": "TOTAL CONNECTIONS", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 36 } },
    {
     "title": "DURABLES - OUTSTANDING EVENTS BY TOPIC",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 }
    },
    {
     "title": "TOPICS - PUBLISHED/CONSUMED - RATE",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 }
    },
    {
     "title": "TOPICS - PUBLISHED/CONSUMED  - EVENTS",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 }
    },
    { "title": "TOPICS - DISK USAGE", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 } }
   ]
  },
  {
   "title": "Terracotta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "collapsed": true,
   "panels": [
    { "title": "Cache Rate", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 } },
    { "title": "Cache Failures", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 } },
    { "title": "Live Object Count", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 } },
    { "title": "Read/Write Operation Rate", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 } },
    { "title": "Offheap Used", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 } },
    { "title": "Disk Storage Used", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 } }
   ]
  }
 ]
}