{
 "title": "METRICS-TO-LOGS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\",namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=~\"$cluster\",namespace=~\"$namespace\"},label_app)"
    }
   },
   {
    "name": "api_name",
    "query": {
     "query": "label_values(sag_apigw_api_tx_count,api_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "INBOUND LAYER - API GATEWAY - HIGHLEVEL OVERVIEW ON ERRORS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "OVERALL API ERROR COUNT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "floor(sum(increase(sag_apigw_tx_error_count[$__range]) > 0) by(code))",
     "legendFormat": "Error Count: {{code}}"
    }
   ]
  },
  {
   "title": "INDIVIDUAL API ERROR COUNT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "floor(increase(sag_apigw_api_tx_error_count{node=~\"$node\",cluster=~\"$cluster\",app=~\"$app\",pod=~\"$pod\",api_name=~\"$api_name\"}[$__range])) > 0",
     "legendFormat": "{{api_name}}_{{api_version}}"
    }
   ]
  },
  {
   "title": "MIDDLEWARE LAYER - MSR - HIGHLEVEL OVERVIEW ON ERRORS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "MSR - HTTP - ERROR VIEW",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(sag_is_service_requests_total{apiCat=~\"API_REST|SERVICE_HTTP\",node=~\"$node\",app=~\"$app\",namespace=~\"$namespace\",cluster=~\"$cluster\",code=~\"4.*|5.*\"}) by(app,code,version,service) > 0",
     "legendFormat": "{{app}}|{{service}}|{{code}}"
    }
   ]
  },
  {
   "title": "LOGS - API GATEWAY & NATIVE LAYERS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "API Gateway Logs [Analytics] - Failed Transactions",
   "type": "logs",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "status: FAILURE AND apiName: $app",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "KUBERNETES POD LOGS ",
   "type": "logs",
   "gridPos": { "h": 15, "w": 11, "x": 12, "y": 24 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "NOT kubernetes.container.name.keyword:istio-proxy AND NOT event.module:system AND NOT kubernetes.namespace:monitoring AND NOT kubernetes.container.name.keyword:microgateway AND kubernetes.pod.name:$pod AND kubernetes.labels.app:$app",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Solution Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "MSR Logs [Interceptor] - Failed Transactions",
   "type": "logs",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 40 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "responseCode: 5.* || responseCode: 4.*",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}