{
 "title": "OPERATIONS TRACER - ISTIO",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Destination Namespace",
    "query": {
     "query": "query_result(sum(istio_requests_total) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total) by (destination_workload_namespace))"
    }
   },
   {
    "name": "workload",
    "label": "Destination Workload",
    "query": {
     "query": "query_result((sum(istio_requests_total{destination_workload_namespace=~\"$namespace\"}) by (destination_workload) or sum(istio_requests_total{source_workload_namespace=~\"$namespace\"}) by (source_workload)) or (sum(istio_tcp_sent_bytes_total{destination_workload_namespace=~\"$namespace\"}) by (destination_workload) or sum(istio_tcp_sent_bytes_total{source_workload_namespace=~\"$namespace\"}) by (source_workload)))"
    }
   },
   { "name": "qrep", "label": "Reporter", "query": { "query": "label_values(reporter)" } },
   {
    "name": "srcns",
    "label": "Source Workload Namespace",
    "query": {
     "query": "query_result(sum(istio_requests_total{reporter=~\"$qrep\", destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\"}) by (source_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=~\"$qrep\", destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\"}) by (source_workload_namespace))"
    }
   },
   {
    "name": "srcwl",
    "label": "Source Workload",
    "query": {
     "query": "query_result(sum(istio_requests_total{reporter=~\"$qrep\", destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload_namespace=~\"$srcns\"}) by (source_workload) or sum(istio_tcp_sent_bytes_total{reporter=~\"$qrep\", destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload_namespace=~\"$srcns\"}) by (source_workload))"
    }
   },
   {
    "name": "dstsvc",
    "label": "Destination Service",
    "query": {
     "query": "query_result(sum(istio_requests_total{reporter=\"source\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\"}) by (destination_service) or sum(istio_tcp_sent_bytes_total{reporter=\"source\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\"}) by (destination_service))"
    }
   },
   {
    "name": "responsecode",
    "label": "Response Code",
    "query": {
     "query": "query_result(sum(istio_requests_total) by(response_code))"
    }
   },
   {
    "name": "workloadapp",
    "label": "Destination Workload App",
    "query": {
     "query": "query_result((sum(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}) by (destination_workload,destination_app) or sum(istio_requests_total{source_workload_namespace=~\"$namespace\"}) by (source_workload,source_app)) or (sum(istio_tcp_sent_bytes_total{destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}) by (destination_workload,destination_app) or sum(istio_tcp_sent_bytes_total{source_workload_namespace=~\"$namespace\"}) by (source_workload,source_app)))"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=~\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=~\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[5m]))"
    }
   ]
  },
  {
   "title": "Incoming Requests By Source And Response Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", reporter=~\"$qrep\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\", response_code=~\"$responsecode\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", reporter=~\"$qrep\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\", response_code=~\"$responsecode\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=~\"$qrep\", connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",response_code!~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=~\"$qrep\", connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=~\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",response_code!~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=~\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Failure Rate (5xx responses) By Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=~\"$qrep\", connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",response_code=~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=~\"$qrep\", connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=~\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",response_code=~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=~\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Volume",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=~\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Outgoing Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=~\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=~\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[5m]))"
    }
   ]
  },
  {
   "title": "Outgoing Requests By Destination And Response Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{destination_principal=~\"spiffe.*\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", reporter=\"source\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{destination_principal!~\"spiffe.*\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", reporter=\"source\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Outgoing Success Rate (non-5xx responses) By Destination",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",response_code!~\"5.*\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service)",
     "legendFormat": "{{ destination_service }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",response_code!~\"5.*\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service)",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  {
   "title": "Outgoing Failure Rate (5xx responses) By Destination",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",response_code=~\"5.*\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service)",
     "legendFormat": "{{ destination_service }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",response_code=~\"5.*\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service)",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  {
   "title": "Outgoing Request Volume",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=~\"$qrep\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "COMPONENT TRACKER",
   "type": "text",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "<iframe  width=\"100%\" height=\"100%\" src=\"http://$node:32400/kiali/console/graph/namespaces/?traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=app&namespaces=$namespace&duration=120&refresh=15000&layout=kiali-dagre&namespaceLayout=kiali-dagre&animation=true&edges=trafficRate%2Cthroughput%2CthroughputRequest%2CtrafficDistribution\"></iframe>"
   }
  },
  {
   "title": "COMPONENT TRACKER",
   "type": "text",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<iframe  width=\"100%\" height=\"100%\" src=\"http://$node:32400/kiali/console/graph/node/namespaces/$namespace/services/$workload?edges=trafficRate%2Cthroughput%2CthroughputRequest%2CtrafficDistribution&edgeMode=all&layout=kiali-dagre&namespaceLayout=kiali-dagre&idleEdges=false&idleNodes=false&injectServiceNodes=true&traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=workload&duration=120&operationNodes=false&refresh=15000&namespaces=$namespace&animation=true\"></iframe>"
   }
  },
  {
   "title": "LOGS",
   "type": "logs",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 76 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "kubernetes.labels.app: $workloadapp  && NOT kubernetes.container.name:\"istio-proxy\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "alertlist",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 76 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) by(app)",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "ALERTS HISTORY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 87 },
   "targets": [
    {
     "expr": "ALERTS_FOR_STATE",
     "legendFormat": "{{alertname}} - Source [{{source_app}}] - Destination [{{destination_app}}]"
    }
   ]
  }
 ]
}