apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: default
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false
    pipeline.ecs_compatibility: disabled
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input 
    {
      beats {
        port => 5044
      }
    }

    filter 
    {
      if [log][file][path] == "/sag/monitoring/trxAudit.log" 
      {            
        json
        {
            source => "message"
            target => "auditdata"
        }     
        mutate 
        {
            remove_field => [ "message", "host", "agent", "input", "ecs","tags", "@version","@timestamp"]
            add_field => 
            { 
                "status" => "%{[auditdata][auditType]}" 
                "creationDate" => "%{[auditdata][timestamp]}"
                "nativeURL" => "%{[auditdata][loggerData][loggerName]}"
                "logMessage" => "%{[auditdata][loggerData][logMessage]}"
                "server" => "%{[auditdata][serverName]}:%{[auditdata][serverPort]}" 
            }
        }
        if [status] == "START"
        {
            mutate
            {
                add_field => {"reqPayload" => "%{[auditdata][docToBeLogged]}"}
            }
        }
        else
        {
            mutate
            {
                add_field => {"resPayload" => "%{[auditdata][docToBeLogged]}"}
            }
        }
        # Ruby section below is for node graph. If node visualization is not required, then below section can be commented!
        # Custom header section will be dynamically mapped and assigned as key value pairs
        ruby
        {
            code => '
              event.get("[auditdata][customHeaders]").each { |k, v|
                  event.set(k, v)
              }

              if event.get("x-transaction-id").nil?; event.set("x-transaction-id", rand(36**10).to_s(36)); end
              '
        }
        prune 
        {
            blacklist_names => ["auditdata"]
        }          
        date 
        {
            match => [ "creationDate", "YYYY-MM-dd HH:mm:ss.SSS" ]
            target => "creationDate"
        }
      }     
    }
   
    output 
    {
        if [log][file][path] == "/sag/monitoring/trxAudit.log"
        {

            elasticsearch  
            {              
                hosts => [ "${ELASTICSEARCH_HOSTS}" ]
                user => "${ELASTICSEARCH_USER}"
                password => "${ELASTICSEARCH_PASSWORD}"
                index => "customlogger_transactionalevents"
                doc_as_upsert => "true"
                action => "update"
                document_id => "%{[x-transaction-id]}_%{[nativeURL]}"
            }
             stdout { codec => rubydebug }
        } 
        else 
        {
                elasticsearch  
                {
                      hosts => [ "${ELASTICSEARCH_HOSTS}" ]
                      user => "${ELASTICSEARCH_USER}"
                      password => "${ELASTICSEARCH_PASSWORD}"
                      index => "logs-%{[@metadata][beat]}"
                }
        }         
    }
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  containers:
  - image: docker.elastic.co/logstash/logstash:7.13.0
    name: logstash
    ports:
    - containerPort: 5044
    env:
    - name: ELASTICSEARCH_HOSTS
      value: "http://es-srv.default.svc.cluster.local:9200"
    - name: ELASTICSEARCH_USER
      value: "elastic"
    - name: ELASTICSEARCH_PASSWORD
      value: "changeme"
    resources: {}
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/logstash/config
    - name: logstash-pipeline-volume
      mountPath: /usr/share/logstash/pipeline
  restartPolicy: OnFailure
  volumes:
  - name: config-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.yml
          path: logstash.yml
  - name: logstash-pipeline-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.conf
          path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  namespace: default
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  type: ClusterIP