apiVersion: v1
kind: Service
metadata:
  labels:
    elastic.service: dp-elasticsearch
  name: dp-elasticsearch
  namespace: insurance
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  type: ClusterIP
  selector:
    elastic.service: dp-elasticsearch
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: dp-elasticsearch-cip
  labels:
    app: dp-elasticsearch-cip
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
  publishNotReadyAddresses: true
  selector:
    elastic.service: dp-elasticsearch
  sessionAffinity: None
  type: ClusterIP