apiVersion: v1
kind: Service
metadata:
  name: assessments
  namespace: insurance
  labels:
    app: assessments
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    app: assessments
    component: msr
  ports:
    - port: 5555
      name: http-server
      targetPort: 5555
      nodePort: 30200
    - port: 5656
      name: https-server
      targetPort: 5656
      nodePort: 30201
  type: NodePort
  sessionAffinity: ClientIP