apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msr-log-storage
  labels:
    app: msr
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi