apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    component: node-exporter
    app: prometheus
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
    nodePort: 31990
  selector:
    component: node-exporter
  sessionAffinity: None
  type: NodePort
