apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-oblty
rules:
- apiGroups: 
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]  
- apiGroups: 
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]   
- apiGroups: 
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs: ["get", "list", "watch"]    
- apiGroups: 
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs: ["get", "list", "watch"]    
- apiGroups: 
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs: ["get", "list", "watch"]   
- apiGroups: 
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs: ["get", "list", "watch"]     
- apiGroups: 
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs: ["get", "list", "watch"]     
- apiGroups: 
  - policy
  resources:
  - poddisruptionbudgets
  verbs: ["get", "list", "watch"]     
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - namespaces
  - configmaps
  - cronjobs.batch
  - endpoints
  - ingresses.extensions
  - jobs.batch
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - replicationcontrollers
  - resourcequotas
  - secrets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-oblty
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: demo-oblty
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring  
