apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  labels:
    app: prometheus
    component: prometheus-server
  namespace: monitoring  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
      component: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus
        component: prometheus-server
    spec:
      containers:   
      - name: prometheus
        image: prom/prometheus
        imagePullPolicy: "IfNotPresent"
        args:
          - --storage.tsdb.retention.time=15d
          - --config.file=/etc/config/prometheus.yml
          - --storage.tsdb.path=/data
          - --web.console.libraries=/etc/prometheus/console_libraries
          - --web.console.templates=/etc/prometheus/consoles
          - --web.enable-lifecycle
        ports:
        - name: web
          containerPort: 9090
        resources:
          limits:
            cpu: "1"
            memory: "1Gi" 
          requests:
            cpu: "0.25"
            memory: "500Mi"       
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 4
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 10                           
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/config/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-config
          mountPath: /etc/config/alerting_rules.yml
          subPath: alerting_rules.yml 
        - name: prometheus-config
          mountPath: /etc/config/recording_rules.yml
          subPath: recording_rules.yml                   
        - name: prometheus-storage
          mountPath: /data
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred    
      volumes:
      - name: prometheus-config
        configMap:
            name: prometheus-server
      - name: prometheus-storage
        persistentVolumeClaim:
            claimName: prometheus-storage