apiVersion: v1
kind: Service
metadata:
    name: prometheus-server
    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9090'
    namespace: monitoring    
spec:
    selector:
        app: prometheus
        component: prometheus-server
    type: NodePort
    ports:
    - port: 9090
      targetPort: 9090 
      nodePort: 32000
      name: http-server