apiVersion: apps/v1
kind: Deployment
metadata: 
  name: staging-tradingnetworks
  namespace: insurance
spec:
  selector:
    matchLabels:
      app: staging-tradingnetworks
      version: v1.0
      component: msr
  replicas: 1
  template:
    metadata:
      labels:
        app: staging-tradingnetworks
        component: msr
        version: v1.0
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "staging-tradingnetworks"        
      containers:      
        - name: insurance-fitness-staging-tradingnetworks-container       
          image: wm.msr.tn.app:r.<TAG>
          imagePullPolicy: IfNotPresent   
        # Resources required for the apigateway to function. CPUs and Memory configurations.
          resources:
            limits:
              cpu: "1"
              memory: "1G" 
            requests:
              cpu: "0.25"
              memory: "500M"  
          env:
          - name: JAVA_MIN_MEM
            value: "256M"
          - name: JAVA_MAX_MEM
            value: "1024M"     
          ports:
            - containerPort: 5555
        # Liveness probe to check whether container is active. Restart happens when liveness probe fails.
          livenessProbe:
            tcpSocket:
              port: 5555
            timeoutSeconds: 5
            initialDelaySeconds: 60
            failureThreshold: 5
            periodSeconds: 20
            successThreshold: 1
        # Readiness probe to check whether pod is ready to serve the requests. Traffic will not be injected unless readiness probes passes.
          readinessProbe:
            tcpSocket:
              port: 5555
            timeoutSeconds: 5
            initialDelaySeconds: 60
            failureThreshold: 5
            periodSeconds: 20
            successThreshold: 1            
        # Volume mount for Terracotta/Integration Server license key.
          volumeMounts:
            - mountPath: /opt/softwareag/IntegrationServer/bin/../config/licenseKey.xml
              subPath: licenseKey.xml
              name: licensekey
            - mountPath: /opt/softwareag/common/conf/terracotta-license.key
              subPath: terracotta-license.key
              name: licensekey
            - name: application-properties
              mountPath: /opt/softwareag/IntegrationServer/application.properties
              subPath: application.properties                
      imagePullSecrets:
        - name: regcred
        - name: sagregcred                
      volumes:
        - name: licensekey
          configMap:
              name: webmethodslicensekeys
        - name: application-properties
          configMap:
              name: staging-tradingnetworks-appconfig