apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-server.monitoring:9090",
                "version": 1
            },
            {
                "name": "Traces-Elasticsearch",
                "editable": true,
                "type": "elasticsearch",
                "access": "proxy",
                "database": "customlogger_transactionalevents",
                "url": "http://api-gateway.insurance:9240",
                "jsonData":
                {
                  "timeField": "creationDate",
                  "esVersion": "8.2.3"
                }
            },
            {
               "access":"proxy",
                "editable": true,
                "name": "Jaeger",
                "orgId": 1,
                "type": "jaeger",
                "url": "http://tracing.monitoring:80",
                "version": 1
            },            

        ]
    }