apiVersion: v1
kind: ConfigMap
metadata:
  name: apigw-script-configmap
data:
  import.sh: |-
    #!/bin/bash
    set -x;
    while [ $(curl -sw '%{http_code}' "http://api-gateway:5555/rest/apigateway/health" -o /dev/null) -ne 200 ]; do
      sleep 2;
    done    
    curl -LJO  https://raw.githubusercontent.com/kplogesh/InsuranceUsecase/6afe962f7b54e82d02a77195ccbbb38dc487bb1d/assets/insurance/insurance-usecase-type-apigw-mgw/applications/apigateway/sourcecode/insurance-apigw-archive.zip
    curl -X POST 'http://api-gateway:5555/rest/apigateway/archive?overwrite=true&preserveAssetState=true' --header 'Content-Type: application/zip' --header 'Accept: application/json' -u Administrator:manage --data-binary '@'insurance-apigw-archive.zip  