FROM wm.msr.tn:10.15
USER sagadmin
ADD --chown=sagadmin tradingnetworks/dev/sourcecode/msr-packages/ /opt/softwareag/IntegrationServer/packages/
ADD --chown=sagadmin tradingnetworks/dev/sourcecode/tn-assets/ExportedData.bin /opt/softwareag/IntegrationServer/packages/WmTN/bin/