apiVersion: v1
kind: Service
metadata:
  labels:
    elastic.service: elasticsearch
  name: elasticsearch
  namespace: insurance
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  type: ClusterIP
  selector:
    elastic.service: elasticsearch
  clusterIP: None
