pipeline {
    agent any 
    stages {
        stage('Build Image') 
        { 
            steps 
            {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh '''      
                    assets/insurance/pipeline/stages/build/build.sh ${BUILD_NUMBER}
                '''
            }
        }
        stage('Staging - Deploy TN Import Job - K8S') 
        { 
            steps 
            {
                withCredentials([file(credentialsId: 'vadigcs62496k8s', variable: 'KUBECONFIG')]) 
                {
                    sh '''
                        echo ${BUILD_NUMBER}
                        kubectl get po
                    '''
                }
            }
        }
        stage('Staging - Deploy MSR - K8S') { 
            steps 
            {
                withCredentials([file(credentialsId: 'vadigcs62496k8s', variable: 'KUBECONFIG')]) 
                {
                    sh '''
                        echo ${BUILD_NUMBER}
                        cd assets/insurance/insurance-usecase-type-apigw-extes/applications/tradingnetworks/staging/manifests
                        sed -i "s/<TAG>/${BUILD_NUMBER}/" tn-deployment.yaml
                        kubectl get po
                    '''
                }
            }
        }
    }
}