pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh '''
                    sh 'echo "*************************"'
                    sh 'echo "************Build********"'
                    sh 'echo "*************************"'
                    sh "chmod +x -R ${env.WORKSPACE}"                
                    assets/insurance/pipeline/stages/build/build.sh
                '''
            }
        }
        stage('Test') { 
            steps {
                echo 'Testing'
            }
        }
        stage('Deploy') { 
            steps {
                echo 'Deploying'
            }
        }
    }
}