pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                sh 'echo "Building.."'
                sh '''
                    echo "I can do more"
                    ls -ltr
                '''
            }
        }
        stage('Test') { 
            steps {
                echo 'Testing'
            }
        }
        stage('Deploy') { 
            steps {
                echo 'Deploying'
            }
        }
    }
}