apiVersion: v1
kind: Service
metadata:
    name: prometheus-alertmanager
    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9093'
    namespace: monitoring
spec:
    selector:
        app: prometheus
        component: "alertmanager"
    type: NodePort
    ports:
    - port: 9093
      targetPort: 9093 
      nodePort: 31999