apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: prometheus-alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |
    global: {}
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 60s
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: '<emailid>'
        from: '<emailid>'
        send_resolved: true
        require_tls: true
        smarthost: <host:port>
        auth_username: <username>
        auth_password: <password>
        auth_identity: '<identity>'
        tls_config:
           insecure_skip_verify: true
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
