apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alertmanager-storage
  namespace: monitoring
  labels:
    app: prometheus
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi