apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: prometheus-alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |
    global: {}
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 3600s
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'logeshwaran.kannanponnurangam@softwareag.com'
        from: 'lka@softwareag.com'
        require_tls: false
        send_resolved: true
        smarthost: mailhost.eur.ad.sag:25
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
