apiVersion: v1
kind: Service
metadata:
  name: points
  namespace: insurance
  labels:
    app: points
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    app: points
    component: msr
  ports:
    - port: 5555
      name: http-server
      targetPort: 5555
      nodePort: 30000
    - port: 5656
      name: https-server
      targetPort: 5656
      nodePort: 30001
  type: NodePort
  sessionAffinity: ClientIP