apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apigw-storage
  labels:
    app: api-gateway
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi