apiVersion: v1
kind: Service
metadata:
  name: memberships
  namespace: insurance
  labels:
    app: memberships
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    app: memberships
    component: msr
  ports:
    - port: 4485
      name: http-microgateway
      targetPort: 4485
      nodePort: 30400
    - port: 5555
      name: http-server
      targetPort: 5555
      nodePort: 30401
  type: NodePort
  sessionAffinity: ClientIP