apiVersion: batch/v1
kind: Job
metadata:
  name: job-asset-import-tradingnetworks 
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false" 
    spec:
      restartPolicy: Never
      containers:
      - name: asset-import-tradingnetworks
        image: wm.msr.tn:10.15
        command: 
        - "sh"
        - "-c"
        - |
          mkdir -p /opt/softwareag/install/bin
          cd /tmp
          cp /tmp/* /scripts/
          cd /scripts
          chmod 755 import.sh
          ./import.sh
        volumeMounts:
          - mountPath: /scripts
            name: create-dir
          - mountPath: /tmp
            name: import-script    
          - mountPath: /opt/softwareag/IntegrationServer/bin/../config/licenseKey.xml
            subPath: licenseKey.xml
            name: licensekey
          - name: application-properties
            mountPath: /opt/softwareag/IntegrationServer/application.properties
            subPath: application.properties   
          - name: setenv-cp  
            mountPath: /opt/softwareag/IntegrationServer/packages/WmTN/bin/setcp.sh
            subPath: setcp.sh        
          - name: setenv   
            mountPath: /opt/softwareag/install/bin/setenv.sh
            subPath: setenv.sh                           
      volumes:
        - name: import-script
          configMap:
              name: tn-script-configmap   
        - name: create-dir
          emptyDir: {}
        - name: licensekey
          configMap:
              name: webmethodslicensekeys
        - name: application-properties
          configMap:
              name: staging-tradingnetworks-appconfig       
        - name: setenv-cp
          configMap:
              name: staging-tradingnetworks-setenv       
        - name: setenv
          configMap:
              name: staging-tradingnetworks-setenv                     