apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  clusterIP: None  
  selector:
    app: kibana
  sessionAffinity: None
  type: ClusterIP   
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-np
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    nodePort: 32100
  selector:
    app: kibana
  sessionAffinity: ClientIP
  type: NodePort 
