apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-apigateway
  labels: 
    app: kibana-apigateway
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.shutdownTimeout: "5s"
    server.basePath: /apigatewayui/dashboardproxy  
    elasticsearch.hosts: '[ "http://elasticsearch-0.elasticsearch:9200","http://elasticsearch-1.elasticsearch:9200","http://elasticsearch-2.elasticsearch:9200" ]'
    monitoring.ui.container.elasticsearch.enabled: true