apiVersion: apps/v1
kind: Deployment
metadata: 
  name: terracotta-management-console
  namespace: insurance
  labels:
    app: caching
    version: 4.4.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caching
      version: 4.4.0
  template:
    metadata:
      labels:
        app: caching
        version: 4.4.0    
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: terracotta-tmc-container
          image: sagintegrationpractice/demo:tmc.4.3.10.v1
          imagePullPolicy: IfNotPresent
          env:
          - name: ACCEPT_EULA
            value: "Y"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi" 
            requests:
              cpu: "0.25"
              memory: "2Gi"
          ports:
            - containerPort: 9889
              name: management
          volumeMounts:
            - name: license-volume
              mountPath: /licenses/license.key
              subPath: license.key 
      imagePullSecrets:
        - name: regcred
        - name: sagregcred          
      volumes:
        - name: license-volume
          configMap:
            name: webmethodslicensekeys                            