apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: universal-messaging-storage
  namespace: insurance
  labels:
    app: messaging
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi