apiVersion: v1
kind: Service
metadata:
  name: customer-portal
  namespace: insurance
  labels:
    app: customer-portal
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    app: customer-portal
    version: v1
  ports:
    - port: 5555
      name: http-server
      targetPort: 5555
      nodePort: 30600
    - port: 5656
      name: https-server
      targetPort: 5656
      nodePort: 30601
  type: NodePort
  sessionAffinity: ClientIP