apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: universal-messaging-storage
  namespace: insurance
  labels:
    app: messaging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi