apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: insurance
  labels:
    app: notifications
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    app: notifications
    version: v1
  ports:
    - port: 5555
      name: http-server
      targetPort: 5555
      nodePort: 30500
    - port: 5656
      name: https-server
      targetPort: 5656
      nodePort: 30501
  type: NodePort
  sessionAffinity: ClientIP