apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-scaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Pods
    pods:
      metric:
        name: sag_is_server_threads
      target:
        type: AverageValue
        averageValue: 10
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 5Gi        
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 70           