apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rewards-deployment-scaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rewards
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Pods
    pods:
      metric:
        name: sag_is_free_memory_bytes
      target:
        type: AverageValue
        averageValue: 201037824